### ISSUE TITLE
Cannot find module './build/Release/eventlog'

### ISSUE THREAD

**Issue by ts00264250** [stephenwvickers/node-windows-eventlog-reader#1]
C:\Users\EkkapolS\Downloads\node-windows-eventlog-reader-master>node index.js
module.js:471
    throw err;
    ^

Error: Cannot find module './build/Release/eventlog'
    at Function.Module._resolveFilename (module.js:469:15)

**Comment by stephenwvickers** [comment]
Hi, how did you install the module before doing this?

**Comment by ts00264250** [comment]
The last message I run from your project.
But if run from my project ,I receive this error ->
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program
Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305
:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:215:12)

2017-07-06 14:49 GMT+07:00 Stephen Vickers <notifications@github.com>:

**Comment by stephenwvickers** [comment]
What version of the following are you using:

 * python?
 * Compiler (i.e. Visual Studio)?
 * node?
 * node-gyp?
 * npm?

Steve

**Comment by ts00264250** [comment]
- python?   = python27
   - Compiler (i.e. Visual Studio)? = Visual Studio Code
   - node? = v6.11.0
   - node-gyp?  = node-gyp@3.6.2
   - npm? = npm@3.10.10


2017-07-10 16:39 GMT+07:00 Stephen Vickers <notifications@github.com>:

**Comment by stephenwvickers** [comment]
Hi, Visual Studio Code is not a compiler (as far as I am aware), can you confirm which compiler you are using?
